version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs: 
  build: 
    docker:       
      - image: circleci/node:12.13.1    
    working_directory: ~/repo
    steps:      
      - checkout
      - run: npm cache clean --force
      - run: npm install
      - run: CI=false npm run build
      - run:
          name: git conf
          command: |
            git config --global user.email "slimani.ibr@gmail.com"
            git config --global user.name "brahim-slimani"
      - add_ssh_keys:
          fingerprints:
            - "20:79:e1:15:9b:6e:d3:ae:f3:37:a8:92:63:7b:c7:1f"
      - run: npm run deploy